version: '3'
services:
  dev:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      # network: host
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '3000:3000'
    # stdin_open: true
    # tty: true
  prod:
    container_name: nextjs-prod
    build:
      target: production
      context: .
      dockerfile: Dockerfile.prod
      # network: host
    # restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '8000:8000'